M48
; DRILL file {KiCad 7.0.2-0} date 2023 October 18, Wednesday 21:21:29
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-10-18T21:21:29-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.2-0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.900
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C1.800
%
G90
G05
T1
X75.28Y-123.653
X78.28Y-123.653
X86.71Y-123.653
X89.71Y-123.653
T2
X142.355Y-65.39
X147.205Y-65.39
T3
X142.055Y-62.36
X147.505Y-62.36
T0
M30
